version: '3.9'

services:
    maestro:
        profiles:
            -   launch
        build: .
        container_name: maestro
        # todo every service should be able to reach from santaclaus with this name (in respective docker compose)
        environment:
            MAESTRO_ADDRESS: ${MAESTRO_ADDRESS}
            MAESTRO_MONGO_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@big-brain:${MONGO}/maestro?authSource=admin
            DOWNLOAD_WAITING_TIME: 86400 # 24 hours (seconds * minutes * hours)
        expose:
            - ${MAESTRO_PORT}
        networks:
            - big-brain
            - users-back:maestro
            - chouf:maestro
        depends_on:
            - big-brain
        restart: always

    big-brain:
        image: mongo:6
        environment:
            MONGO_INITDB_DATABASE: ${MAESTRO_MONGO_DB}
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
        expose:
            - ${MONGO_PORT}
        ports:
            - ${MONGO_PORT}:${MONGO_PORT}
        networks:
            - big-brain
        volumes:
            - big-brain:/data/db
        restart: always

    big-brain-loader:
        build:
            context: datasets
            dockerfile: Dockerfile.big-brain-loader
        environment:
            MONGO_LOGS_NAME: logs
            MONGO_LOGS_URI: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@big-brain:${MAESTRO_PORT}/logs?authSource=admin
        networks:
            - big-brain
        depends_on:
            - big-brain
        restart: on-failure

    documentation:
        profiles:
            -   documentation # todo change this in github actions
        build:
            context: .
            dockerfile: Dockerfile.documentation
        ports:
            - 50051:80

networks:
    big-brain: null
    users-back:maestro:
        external: true
    chouf:maestro:
        external: true

volumes:
    big-brain: null