version: '3.9'

services:
    maestro:
        build: .
        container_name: maestro
        environment:
            MAESTRO_PORT: $MAESTRO_PORT
            MAESTRO_MONGO_URL: mongodb://maestro_admin:maestro_admin_password@mongo:27017/maestro?authSource=admin
        expose:
            - $MAESTRO_PORT
        networks:
            - mongo
        depends_on:
            - mongo
        restart: on-failure

    mongo:
        image: mongo:6
        environment:
            MONGO_INITDB_DATABASE: maestro
            MONGO_INITDB_ROOT_USERNAME: maestro_admin
            MONGO_INITDB_ROOT_PASSWORD: maestro_admin_password
        expose:
            - 27017
        networks:
            - mongo
        volumes:
            - mongo:/data/db
        restart: always

networks:
    mongo: null

volumes:
    mongo: null
