FROM ubuntu:22.04 AS builder

# Requirements
RUN apt-get update && apt-get install -y \
    cmake       \
    g++         \
    doxygen     \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy sources
COPY cmake /app/cmake
COPY CMakeLists.txt /app
COPY include /app/include
COPY src /app/src
COPY docs /app/docs

# Build
RUN cmake -D doxygen=true -S . -B build
RUN make -C build doxygen


# Run
FROM nginx:1.21

COPY --from=builder /app/docs/Doxygen/html /usr/share/nginx/html