version: '3.9'

services:
    maestro:
        profiles:
            - launch
        build: .
        container_name: maestro
        env_file:
            - ${MAESTRO_ENV_FILE}
        environment:
            DOWNLOAD_WAITING_TIME: 86400 # 24 hours (seconds * minutes * hours)
        ports:
            - ${MAESTRO_PORT}:${MAESTRO_PORT}
        networks:
            - maestro
            - users-back:maestro
            - chouf:maestro
            - maestro:santaclaus
            - maestro:vault
            - maestro:bugle
        depends_on:
            - mongo
        restart: unless-stopped

    mongo:
        profiles:
            - launch
            - mongo
        image: mongo:6
        environment:
            MONGO_INITDB_DATABASE: ${MAESTRO_MONGO_DB}
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
        ports:
            - ${MONGO_PORT}:27017
        networks:
            - maestro
            - users-back:maestro
            - maestro:santaclaus
            - chouf:maestro
            - maestro:bugle
        volumes:
            - mongo:/data/db
        restart: unless-stopped

    documentation:
        profiles:
            - documentation # todo change this in github actions
        build:
            context: .
            dockerfile: Dockerfile.documentation
        ports:
            - 50051:80

networks:
    maestro: null
    users-back:maestro:
        external: true
    chouf:maestro:
        external: true
    maestro:santaclaus:
        external: true
    maestro:vault:
        external: true
    maestro:bugle:
        external: true

volumes:
    mongo:
        name: ${MONGO_VOLUME}
