version: '3.9'

services:
    maestro:
        build: .
        container_name: maestro
        environment:
            MAESTRO_ADDRESS: "[::]:8080"
            MAESTRO_MONGO_URL: mongodb://admin:big_brain@big-brain:27017/maestro?authSource=admin
            DOWNLOAD_WAITING_TIME: 86400 # 24 hours (seconds * minutes * hours)
        expose:
            - 8080
        networks:
            - big-brain
            - users-back:maestro
        depends_on:
            - big-brain
        restart: always

    big-brain:
        image: mongo:6
        environment:
            MONGO_INITDB_DATABASE: maestro
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: big_brain
        expose:
            - 27017
        networks:
            - big-brain
        volumes:
            - big-brain:/data/db
        restart: always

    big-brain-loader:
        build:
            context: datasets
            dockerfile: Dockerfile.big-brain-loader
        environment:
            MONGO_LOGS_NAME: logs
            MONGO_LOGS_URI: mongodb://admin:big_brain@big-brain:27017/logs?authSource=admin
        networks:
            - big-brain
        depends_on:
            - big-brain
        restart: on-failure

    documentation:
        build:
            context: .
            dockerfile: Dockerfile.documentation
        ports:
            - 50051:80

networks:
    big-brain:
        external: true
    users-back:maestro:
        external: true

volumes:
    big-brain: null
