version: '3.9'

services:
    maestro:
        build: .
        environment:
            MAESTRO_ADDRESS: "[::]:8080"
            MAESTRO_MONGO_URL: mongodb://maestro_admin:maestro_admin_password@mongo:27017/maestro?authSource=admin
        expose:
            - 8080
        networks:
            - mongo
            - users-back:maestro
        depends_on:
            - mongo
        restart: on-failure

    mongo:
        image: mongo:6
        environment:
            MONGO_INITDB_DATABASE: maestro
            MONGO_INITDB_ROOT_USERNAME: maestro_admin
            MONGO_INITDB_ROOT_PASSWORD: maestro_admin_password
        expose:
            - 27017
        networks:
            - mongo
        volumes:
            - mongo:/data/db
        restart: always

    documentation:
        build:
            context: .
            dockerfile: Dockerfile.documentation
        ports:
            - 50051:80

networks:
    mongo: null
    users-back:maestro:
        external: true

volumes:
    mongo: null
