version: '3.9'

services:
    maestro:
        build: .
        environment:
            MAESTRO_PORT: 8080
            MAESTRO_MONGO_URL: mongodb://maestro_admin:maestro_admin_password@mongo:27017/maestro?authSource=admin
        ports:
            - 127.0.0.1:8080:8080
        networks:
            - mongo
        depends_on:
            - mongo
        restart: always

    mongo:
        image: mongo:6
        environment:
            MONGO_INITDB_DATABASE: maestro
            MONGO_INITDB_ROOT_USERNAME: maestro_admin
            MONGO_INITDB_ROOT_PASSWORD: maestro_admin_password
        ports:
            - 127.0.0.1:27017:27017
        networks:
            - mongo
        volumes:
            - mongo:/data/db
        restart: always

networks:
    mongo: null

volumes:
    mongo: null
