version: '3.9'

services:
    maestro:
        profiles:
            - launch
        build: .
        container_name: maestro
        # todo every service should be able to reach from santaclaus with this name (in respective docker compose)
        environment:
            MAESTRO_ADDRESS: ${MAESTRO_ADDRESS}
            MAESTRO_MONGO_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:${MONGO_PORT}/maestro?authSource=admin
            DOWNLOAD_WAITING_TIME: 86400 # 24 hours (seconds * minutes * hours)
        expose:
            - ${MAESTRO_PORT}
        networks:
            - mongo
            - users-back:maestro
            - chouf:maestro
        depends_on:
            - mongo
        restart: always

    mongo:
        profiles:
            - launch
            - mongo
        image: mongo:6
        environment:
            MONGO_INITDB_DATABASE: ${MAESTRO_MONGO_DB}
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
        ports:
            - ${MONGO_PORT}:${MONGO_PORT}
        networks:
            - mongo
        volumes:
            - mongo:/data/db
        restart: always

    mongo-loader:
        profiles:
            - launch
            - mongo
        build:
            context: datasets
            dockerfile: Dockerfile.mongo-loader
        environment:
            MONGO_LOGS_NAME: logs
            MONGO_LOGS_URI: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:${MAESTRO_PORT}/logs?authSource=admin
        networks:
            - mongo
        depends_on:
            - mongo
        restart: on-failure

    documentation:
        profiles:
            - documentation # todo change this in github actions
        build:
            context: .
            dockerfile: Dockerfile.documentation
        ports:
            - 50051:80

networks:
    mongo: null
    users-back:maestro:
        external: true
    chouf:maestro:
        external: true

volumes:
    mongo:
        name: ${MONGO_VOLUME}