name: Functional tests

on:
  push:
    branches:
      - main
      - develop
      - github-actions/functional-tests
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        indexes: [ 1 ]
    steps:
      - name: Cache build
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            build
            /opt/mongo
            third_parties
          key: ${{ runner.os }}-functional_tests-build

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.REPO_PROTOBUF_INTERFACES_TOKEN }}
          # secret containing a token allowing access to private repo (protobuf-interface submodule)

      - name: Generate Makefile
        run: cmake -D functional_tests=true -S . -B build

      - name: Build
        run: make -C build functional_tests

      - name: Run functional tests
        run: |
          ./build/functional_tests ${{ matrix.indexes }} > $GITHUB_STEP_SUMMARY

      - name: Result
        if: always()
        run: |
          if [ -f $GITHUB_STEP_SUMMARY ]; then
            cat $GITHUB_STEP_SUMMARY
          fi