name: System tests

on:
  push:
    branches:
      - main
      - develop

jobs:
  notify:
    runs-on: ubuntu-22.04

    steps:
    - name: Call system-tests repository workflow
      env:
        SYSTEM_TESTS_REPO: Nuage-Malin/system-tests
        SYSTEM_TESTS_BRANCH: main
        WORKFLOW_FILENAME: system_tests.yml
      run: |
        curl -L -X POST \
            -H "Accept: application/vnd.github+json"    \
            -H "Authorization: token ${{ secrets.SUBMODULES_TOKEN }}"   \
            -H "X-GitHub-Api-Version: 2022-11-28"   \
            https://api.github.com/repos/${{ env.SYSTEM_TESTS_REPO }}/actions/workflows/${{ env.WORKFLOW_FILENAME }}/dispatches \
            -d '{"ref":"${{ env.SYSTEM_TESTS_BRANCH }}"}'