name: Unit tests

on:
  push:
    branches:
      - main
      - develop
      - github-actions/unit-tests
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Cache build
        uses: actions/cache@v3
        with:
          path: |
            build
            /opt/mongo
            third_parties
          key: ${{ runner.os }}-unit_tests-build

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.REPO_PROTOBUF_INTERFACES_TOKEN }}
          # secret containing a token allowing access to private repo (protobuf-interface submodule)

      - name: Generate Makefile
        run: cmake -D unit_tests=true -S . -B build

      - name: Build
        run: make -C build unit_tests

      - name: Run MongoDB
        run: docker run -d -p 27017:27017 -e MONGO_INITDB_DATABASE=maestro -e MONGO_INITDB_ROOT_USERNAME=maestro_admin -e MONGO_INITDB_ROOT_PASSWORD=maestro_admin_password mongo:6

      - name: Run maestro
        run: ./build/maestro &
        env:
          MAESTRO_ADDRESS: "[::]:8080"
          MAESTRO_MONGO_URL: mongodb://maestro_admin:maestro_admin_password@localhost:27017/maestro?authSource=admin

      - name: Run unit tests
        run: |
          ./build/unit_tests > $GITHUB_STEP_SUMMARY
          cat $GITHUB_STEP_SUMMARY
        env:
          MAESTRO_TESTS_HOST: localhost
          MAESTRO_TESTS_PORT: 8080