name: Compile and execute unit tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.REPO_PROTOBUF_INTERFACES_TOKEN }}
          # secret containing a token allowing access to private repo (protobuf-interface submodule)

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.12
        with:
          cmake-version: '3.17.x'

      - name: Meta build (generate Makefile)
        run: |
          mkdir -p build
          cmake -D unit_tests=true -S . -B build

      - name: Build
        run: make -C build unit_tests

      - name: cache
        uses: actions/cache@v3
        id: cache
        with:
          path: ./
          key: cache_key_unit_tests_build

  tests:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: cache
        uses: actions/cache@v3
        id: cache
        with:
          path: ./
          key: cache_key_unit_tests_build

      - name: Check if cache missed
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          echo "::error title=Cache miss::Could not retrieve cache from build unit tests job"

      - name: Run unit tests
        run: cd build && ctest
      #    run: ./unit_tests