name: Compile and execute unit tests

on:
  push:
    branches:
      - main
      - develop
      - github-actions/unit-tests
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.REPO_PROTOBUF_INTERFACES_TOKEN }}
          # secret containing a token allowing access to private repo (protobuf-interface submodule)

      - name: Cache build
        uses: actions/cache@v3
        with:
          path: |
            build
            /opt/mongo
            third_parties
          key: ${{ runner.os }}-unit_tests-build

      - name: Generate Makefile
        run: |
          mkdir -p build
          cmake -D unit_tests=true -S . -B build

      - name: Build
        run: make -C build unit_tests

      - name: Run unit tests
        run: ./build/unit_tests