name: Unit tests

on:
  workflow_run:
    workflows: [ "Check compilation" ]
    branches:
      - main
      - develop
    types:
      - completed

jobs:
  unit-tests:
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt-get install -y \
            build-essential       \
            autoconf              \
            libtool               \
            pkg-config            \
            libssl-dev            \
            libsasl2-dev          \
            libmongoc-dev         \
            libmongoc-doc         \
            libstdc++-12-dev      \
            libmongoc-1.0-0       \
            libbson-1.0-0         \

      - name: Cache project
        uses: actions/cache@v3
        with:
          path: ./third_parties
          key: ${{ runner.os }}-unit_tests

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.SUBMODULES_TOKEN }}

      - name: Run MongoDB & maestro & unit tests
        run: ./scripts/unit_tests.sh --cmake --build --local --mongo